openapi: 3.0.3
info:
  title: Inventory Management API
  description: API for managing categories, products, and sales.
  version: 1.0.0

servers:
  - url: http://localhost:8081/api/v1
    description: Local server

security:
  - jwt: []

paths:

  /category/all:
    get:
      tags:
        - Category
      operationId: getAllCategories
      summary: Get all categories
      responses:
        'default':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDTO'
  /category:
    get:
      tags:
        - Category
      operationId: CategoriesPerPage
      summary: Get Categories by page number
      #x-spring-paginated: true
      parameters:
        - in: query
          name: page
          description: number of page
          required: true
          schema:
            type: integer
            example: '1'
      responses:
        'default':
          description: A list of categories
          content:
            application/json:
              schema:
                type: CategoryPageDTO
  /category/{id}:
    get:
      tags:
        - Category
      operationId: getCategoryById
      summary: Get Category by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
        '400':
          description: Category not found
  /category/add:
    post:
      tags:
        - Category
      operationId: addCategory
      summary: Create a new Category
      requestBody:
        description: Category to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDTO'
      responses:
        '200':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
  /category/edit/{id}:
    put:
      tags:
        - Category
      operationId: editCategory
      summary: Update a category
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Category
      requestBody:
        description: Updated category data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDTO'
      responses:
        '200':
          description: Category updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
        '400':
          description: Category not found
  /category/delete/{id}:
    delete:
      tags:
        - Category
      operationId: deleteCategory
      summary: Delete a Category
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Category
      responses:
        '200':
          description: Category deleted
          content:
            text/plain:
              schema:
                type: string
                example: "Category deleted successfully."
        '400':
          description: Invalid Category value
  /category/search:
    get:
      tags:
        - Category
      operationId: getCategoriesByName
      summary: Get categories by name
      parameters:
        - in: query
          name: name
          description: name of category
          required: true
          schema:
            type: string
            example: 'phones'
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDTO'
  /product/all:
    get:
      tags:
        - Product
      operationId: getAllProducts
      summary: Get all Products
      responses:
        '200':
          description: A list of Products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDTO'
  /product/{id}:
    get:
      tags:
        - Product
      operationId: getProductById
      summary: Get Product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
        '400':
          description: Product not found
  /product/add:
    post:
      tags:
        - Product
      operationId: addProduct
      summary: Create a new Product
      requestBody:
        description: Product to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
      responses:
        '200':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
  /product/edit/{id}:
    put:
      tags:
        - Product
      operationId: editProduct
      summary: Update a Product
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Product
      requestBody:
        description: Updated Product data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
      responses:
        '200':
          description: Product updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
  /product/delete/{id}:
    delete:
      tags:
        - Product
      operationId: deleteProduct
      summary: Delete a Product
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Product
      responses:
        '200':
          description: Product deleted
          content:
            text/plain:
              schema:
                type: string
                example: "Product deleted successfully."
        '400':
          description: Invalid Product value
  /product/search:
    get:
      tags:
        - Product
      operationId: getProductsByName
      summary: Get Product by name
      parameters:
        - in: query
          name: name
          description: name of Product
          required: true
          schema:
            type: string
            example: 'phones'
      responses:
        '200':
          description: A list of Product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDTO'
  /product/filtred:
    get:
      summary: Get all filtered products
      description: Retrieve filtered products with pagination and sorting options.
      operationId: searchForProductsByAnyColumn
      parameters:
        - in: query
          name: input
          schema:
            type: string
          required: true
          description: The input to filter products by their name.

        - in: query
          name: sort
          schema:
            type: string
          required: true
          description: The field to sort by. Defaults to "id" if set to "undefined".

        - in: query
          name: order
          schema:
            type: string
            enum: [ asc, desc ]
          required: true
          description: The sorting order (ascending or descending). Defaults to "asc" if blank or invalid.

        - in: query
          name: page
          schema:
            type: integer
            default: 1
          required: true
          description: The page number to retrieve (1-based index).

        - in: query
          name: per_page
          schema:
            type: integer
            minimum: 1
          required: true
          description: The number of items per page.

      responses:
        '200':
          description: A paginated list of filtered products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPageDTO'
        '400':
          description: Invalid input or parameters
        '500':
          description: Internal server error

  /sale/all:
    get:
      tags:
        - Sale
      operationId: getAllSales
      summary: Get all Sales
      responses:
        '200':
          description: A list of Sales
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SaleDTO'
  /sale/{id}:
    get:
      tags:
        - Sale
      operationId: getSaleById
      summary: Get Sale by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sale details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleDTO'
        '400':
          description: Sale not found
  /sale/add:
    post:
      tags:
        - Sale
      operationId: addSale
      summary: Create a new Sale
      requestBody:
        description: Sale to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaleDTO'
      responses:
        '200':
          description: Sale created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleDTO'
        '400':
          description: insufficient quantity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /sale/edit/{id}:
    put:
      tags:
        - Sale
      operationId: editSale
      summary: Update a Sale
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Sale
      requestBody:
        description: Updated Sale data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaleDTO'
      responses:
        '200':
          description: Sale updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleDTO'
        '404':
          description: Sale not found
        '400':
          description: Insufficient product quantity
          content:
            text/plain:
              schema:
                type: string
  /sale/delete/{id}:
    delete:
      tags:
        - Sale
      operationId: deleteSale
      summary: Delete a Sale
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Sale
      responses:
        '200':
          description: Sale deleted
          content:
            text/plain:
              schema:
                type: string
                example: "Sale deleted successfully."
        '400':
          description: Sale not found
  /sale/search:
    get:
      tags:
        - Sale
      operationId: getSalesByName
      summary: Get Sale by name
      parameters:
        - in: query
          name: name
          description: name of Sale
          required: true
          schema:
            type: string
            example: 'sale-1'
      responses:
        '200':
          description: A list of Sales
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SaleDTO'
  /user/login:
    post:
      tags:
        - Authentication
      summary: Logs usern into the system
      description: ''
      operationId: login
      requestBody:
        description: User Login
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginPayload'
      responses:
        'default':
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the usern
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: Invalid username/password supplied
  /user/logout:
    get:
      tags:
        - Authentication
      summary: Logs out current logged in user session
      description: ''
      operationId: logout
      parameters: [ ]
      responses:
        default:
          description: successful operation
components:
  securitySchemes:
    jwt:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
  schemas:
    CategoryDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          minLength: 1  # Not empty
    ProductDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        productName:
          type: string
          minLength: 1  # Not empty
        productCode:
          type: string
          minLength: 1  # Not empty
        description:
          type: string
        quantity:
          type: integer
          format: int64
          minimum: 1    # The value must be >= 0
        unitBuyPrice:
          type: number
          format: double
          minimum: 0.0
        unitSellPrice:
          type: number
          format: double
          minimum: 0.0
        buyDate:
          type: string
          format: date
        category:
          $ref: '#/components/schemas/CategoryDTO'
    SaleDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
          minLength: 1  # Not empty
        saleDate:
          type: string
          format: date
        saleQuantity:
          type: integer
          format: int64
          minimum: 1
        discount:
          type: number
          format: double
          minimum: 0.0
        product:
          $ref: '#/components/schemas/ProductDTO'
      required:
        - description
        - saleDate
        - saleQuantity
        - discount
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
          example: John
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        usernStatus:
          type: integer
          description: usern Status
          format: int32
        deleted:
          type: boolean
          example: true
        active:
          type: boolean
          example: true
        roles:
          type: string
          example: 'ADMIN|STAFF'
      required:
        - username
        - password
        - status
    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          example: "ERR_400"
        message:
          type: string
          example: "Invalid item ID provided"
      required:
        - errorCode
        - message

    LoginPayload:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    Token:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          example: 1221
        token:
          type: string
          example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0IiwiYXVkIjpbImFkbWluIl0sImlzcyI6Im1hc29uLm1ldGFtdWcubmV0IiwiZXhwIjoxNTc0NTEyNzY1LCJpYXQiOjE1NjY3MzY3NjUsImp0aSI6ImY3YmZlMzNmLTdiZjctNGViNC04ZTU5LTk5MTc5OWI1ZWI4YSJ9.EVcCaSqrSNVs3cWdLt-qkoqUk7rPHEOsDHS8yejwxMw"
        expiration:
          type: integer
          format: int64
          example: 1235216897543
        roles:
          type: string
          example: "ADMIN;SUPERVISOR;STAFF"
        firstname:
          type: string
          example: ismail
        lastname:
          type: string
          example: rzouki
        username:
          type: string
          example: ir91995

    CommonResponse:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
          example: Exception Details from the API
        details:
          type: string
          example: "Common Response returned from the server"

    ProductPageDTO:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductDTO'
        totalCount:
          type: integer
          format: int64
          description: Total number of products available
        pageIndex:
          type: integer
          format: int64
          description: The current page index (0-based)

